import type { Metadata } from "next";
import HomePage from "@/components/homePage";

export const metadata: Metadata = {
  title: "WRTeam",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <HomePage />
  );
}
